# Generated by Django 4.2.30 on 2026-09-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=40)),
                ('summary', models.TextField()),
                ('highlights', models.TextField(help_text='One highlight per line')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('product_interest', models.CharField(choices=[('tempered-glass', 'Tempered glass'), ('lcd-screens', 'LCD screens'), ('chargers', 'Chargers'), ('cables', 'Cables'), ('bluetooth-headphones', 'Bluetooth headphones'), ('mixed-container', 'Multiple / mixed container'), ('custom-odm', 'Custom ODM project')], max_length=40)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True, help_text='One specification per line')),
                ('moq', models.CharField(blank=True, max_length=80)),
                ('lead_time', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
